name: APP dev
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Write GitHub ref
      id: write_ref
      run: echo ${{ github.ref }}
    - name: Test contains
      id: test-contains
      if: contains(github.ref, 'mai')
      run: echo OK
