name: APP dev
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Tests
    runs-on: ubuntu
    
    steps:
    - name: Test contains
      id: test-contains
      if: contains(github.ref, 'act')
      run: echo OK
